name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Build
        run: bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
